name:                homework3
version:             0.1.0.0
github:              "ycjungSubhuman/homework3"
license:             BSD3
author:              "Yuchoel Jung"
maintainer:          "ycjung@postech.ac.kr"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ycjungSubhuman/homework3#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- random

library:
  source-dirs: src

executables:
  Twomoon:
    main:                TwoMoon.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is TwoMoon
    dependencies:
    - homework3

  Mnist:
    main:                Mnist.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Mnist
    dependencies:
    - homework3

tests:
  homework3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework3
